import type { MetadataRoute } from "next";

export const dynamic = "force-static";

const baseUrl = "https://floatsanywhere.com";

const routes = [
  "/",
  "/about/",
  "/about/accessibility/",
  "/about/careers/",
  "/about/contact/",
  "/about/leadership/",
  "/about/press/",
  "/about/the-shift/",
  "/contact-sales/",
  "/developers/",
  "/developers/api-overview/",
  "/developers/documentation/",
  "/developers/free-developer-account/",
  "/enterprise/",
  "/enterprise/security/",
  "/enterprise/services/",
  "/floats-impact/",
  "/get-a-demo/",
  "/industries/",
  "/industries/automotive/",
  "/industries/financial-services/",
  "/industries/government-and-cultural/",
  "/industries/luxury-retail/",
  "/industries/sports-and-entertainment/",
  "/industries/technology/",
  "/legal/",
  "/legal/cookie-policy/",
  "/legal/cookie-settings/",
  "/legal/data-processing-attachment/",
  "/legal/gdpr/",
  "/legal/intellectual-property/",
  "/legal/modern-slavery-statement/",
  "/legal/privacy-notice/",
  "/legal/reasonable-use-policy/",
  "/legal/terms-of-use/",
  "/partners/",
  "/partners/become-a-partner/",
  "/partners/login/",
  "/plans-and-pricing/",
  "/plans-and-pricing/api-plans/",
  "/plans-and-pricing/bundled-activation/",
  "/plans-and-pricing/intelligence-layer-only/",
  "/plans-and-pricing/retainer/",
  "/products/",
  "/products/action-reporting/",
  "/products/digital-activation-zones/",
  "/products/experience-layer/",
  "/products/immersive-booths/",
  "/products/integrations/",
  "/products/realmspace/",
  "/products/realmspace/api/",
  "/products/realmspace/booths-and-zones/",
  "/products/realmspace/insight-reports/",
  "/products/realmspace/natural-language-query/",
  "/products/realmspace/predictive-roi/",
  "/products/realmspace/privacy/",
  "/resources/",
  "/resources/benchmarks/",
  "/resources/blog/",
  "/resources/case-studies/",
  "/resources/events/",
  "/resources/glossary/",
  "/resources/guides/",
  "/resources/research/",
  "/resources/webinars/",
  "/solutions/",
  "/solutions/brand-activations/",
  "/solutions/measurable-roi/",
  "/solutions/retail-flagship/",
  "/solutions/sponsor-measurement/",
  "/solutions/trade-shows-and-conferences/",
  "/solutions/venue-operations/",
  "/support/",
  "/support/community/",
  "/support/getting-started/",
  "/support/knowledge-base/",
  "/support/status/",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    changeFrequency: route === "/" ? "weekly" : "monthly",
    priority: route === "/" ? 1 : route.split("/").filter(Boolean).length === 1 ? 0.8 : 0.6,
  }));
}
